model: YoloAssets/BaseModels\Fresh-v12-extraLarge.pt
batch: 0.9
data: YoloAssets/dataset/data.yaml
device: cuda
epochs: 100
imgsz: 640
name: ongoing_run_20250909155716
plots: true
project: YoloAssets/Trains
save: true
patience: 100
optimizer: auto
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
dfl: 1.5
resume: false
